/**
 * Autogenerated by Avro
 *
 * DO NOT EDIT DIRECTLY
 */
package com.James.avroProto;

@SuppressWarnings("all")
@org.apache.avro.specific.AvroGenerated
public interface avrpRequestProto {
  public static final org.apache.avro.Protocol PROTOCOL = org.apache.avro.Protocol.parse("{\"protocol\":\"avrpRequestProto\",\"namespace\":\"com.James.avroProto\",\"types\":[{\"type\":\"record\",\"name\":\"Message\",\"fields\":[{\"name\":\"param\",\"type\":\"string\"},{\"name\":\"RequestName\",\"type\":\"string\"}]}],\"messages\":{\"send\":{\"request\":[{\"name\":\"message\",\"type\":\"Message\"}],\"response\":\"string\"}}}");
  /**
   */
  java.lang.CharSequence send(com.James.avroProto.Message message) throws org.apache.avro.AvroRemoteException;

  @SuppressWarnings("all")
  public interface Callback extends avrpRequestProto {
    public static final org.apache.avro.Protocol PROTOCOL = com.James.avroProto.avrpRequestProto.PROTOCOL;
    /**
     * @throws java.io.IOException The async call could not be completed.
     */
    void send(com.James.avroProto.Message message, org.apache.avro.ipc.Callback<java.lang.CharSequence> callback) throws java.io.IOException;
  }
}